### ISSUE TITLE
Support for TCW220

### ISSUE THREAD

**Issue by manfred-schnabi** [astrandb/teracom_hass#68]
Do you intend to support the TCW220 in near future? This would be great. TCW220 is similar to TCW241: Two relais, analog and digital inputs instead of four.

**Comment by astrandb** [comment]
I will take a look.

**Comment by manfred-schnabi** [comment]
Thank you...

**Comment by manfred-schnabi** [comment]
I updated and integrated my TCW220 in HA and tested it. It works fine. Thank you very much.
